### ISSUE TITLE
关于python3的支持

### ISSUE THREAD

**Issue by wiwengweng** [Superman-Tiger/Using-HMM-to-solve-the-problem-of-vehicle-trajectory-prediction#1]
请问在python3里面怎样加载pkl模型？原有模型基于2.7生成，在python3里面会报错，应该怎么兼容呢？

````
Traceback (most recent call last):
  File "prediction_fly.py", line 278, in <module>
    main()
  File "prediction_fly.py", line 187, in main
    plocations = predicted_pointN_byV(5,'../middata/t1253.txt')
  File "prediction_fly.py", line 137, in predicted_pointN_byV
    modelv = joblib.load(model)
  File "/root/vehicle-trajectory-prediction-HMM-master/venv/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/root/vehicle-trajectory-prediction-HMM-master/venv/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 541, in _unpickle
    raise new_exc
ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.

````
谢谢

**Comment by lhyfst** [comment]
joblib 不支持跨Python版本使用。你可以使用pickle代替joblib保存文件。而且要在保存文件的时候指定protocol。否则还会报相同的错误。

**Comment by wiwengweng** [comment]
嗯，是个好办法～感谢
